using System;

namespace ASOFT.CoreAI.Entities
{
    public class ONT1042ViewModel
    {
        public Guid APK { get; set; }
        public Guid? APK_ONT1040 { get; set; }
        public string? DivisionID { get; set; }
        public string? PromptID { get; set; }
        public string? PromptName { get; set; }
        public string? ModuleID { get; set; }
        public string? PromptBussiness { get; set; }
        public string? PromptHandle { get; set; }
        public string? PromptInput { get; set; }
        public string? PromptOutput { get; set; }
        public double Version { get; set; }
        public string? Description { get; set; }
        public byte? Disabled { get; set; }
        public DateTime? CreateDate { get; set; }
        public string? CreateUserID { get; set; }
        public DateTime? LastModifyDate { get; set; }
        public string? LastModifyUserID { get; set; }
        #region
        public Guid? ParameterID01 { get; set; }
        public Guid? ParameterID02 { get; set; }
        public Guid? ParameterID03 { get; set; }
        public Guid? ParameterID04 { get; set; }
        public Guid? ParameterID05 { get; set; }
        public Guid? ParameterID06 { get; set; }
        public Guid? ParameterID07 { get; set; }
        public Guid? ParameterID08 { get; set; }
        public Guid? ParameterID09 { get; set; }
        public Guid? ParameterID10 { get; set; }
        public Guid? ParameterID11 { get; set; }
        public Guid? ParameterID12 { get; set; }
        public Guid? ParameterID13 { get; set; }
        public Guid? ParameterID14 { get; set; }
        public Guid? ParameterID15 { get; set; }
        public Guid? ParameterID16 { get; set; }
        public Guid? ParameterID17 { get; set; }
        public Guid? ParameterID18 { get; set; }
        public Guid? ParameterID19 { get; set; }
        public Guid? ParameterID20 { get; set; }
        public Guid? ParameterID21 { get; set; }
        public Guid? ParameterID22 { get; set; }
        public Guid? ParameterID23 { get; set; }
        public Guid? ParameterID24 { get; set; }
        public Guid? ParameterID25 { get; set; }
        public Guid? ParameterID26 { get; set; }
        public Guid? ParameterID27 { get; set; }
        public Guid? ParameterID28 { get; set; }
        public Guid? ParameterID29 { get; set; }
        public Guid? ParameterID30 { get; set; }
        public Guid? ParameterID31 { get; set; }
        public Guid? ParameterID32 { get; set; }
        public Guid? ParameterID33 { get; set; }
        public Guid? ParameterID34 { get; set; }
        public Guid? ParameterID35 { get; set; }
        public Guid? ParameterID36 { get; set; }
        public Guid? ParameterID37 { get; set; }
        public Guid? ParameterID38 { get; set; }
        public Guid? ParameterID39 { get; set; }
        public Guid? ParameterID40 { get; set; }
        public Guid? ParameterID41 { get; set; }
        public Guid? ParameterID42 { get; set; }
        public Guid? ParameterID43 { get; set; }
        public Guid? ParameterID44 { get; set; }
        public Guid? ParameterID45 { get; set; }
        public Guid? ParameterID46 { get; set; }
        public Guid? ParameterID47 { get; set; }
        public Guid? ParameterID48 { get; set; }
        public Guid? ParameterID49 { get; set; }
        public Guid? ParameterID50 { get; set; }
        public Guid? ParameterID51 { get; set; }
        public Guid? ParameterID52 { get; set; }
        public Guid? ParameterID53 { get; set; }
        public Guid? ParameterID54 { get; set; }
        public Guid? ParameterID55 { get; set; }
        public Guid? ParameterID56 { get; set; }
        public Guid? ParameterID57 { get; set; }
        public Guid? ParameterID58 { get; set; }
        public Guid? ParameterID59 { get; set; }
        public Guid? ParameterID60 { get; set; }
        public Guid? ParameterID61 { get; set; }
        public Guid? ParameterID62 { get; set; }
        public Guid? ParameterID63 { get; set; }
        public Guid? ParameterID64 { get; set; }
        public Guid? ParameterID65 { get; set; }
        public Guid? ParameterID66 { get; set; }
        public Guid? ParameterID67 { get; set; }
        public Guid? ParameterID68 { get; set; }
        public Guid? ParameterID69 { get; set; }
        public Guid? ParameterID70 { get; set; }
        public Guid? ParameterID71 { get; set; }
        public Guid? ParameterID72 { get; set; }
        public Guid? ParameterID73 { get; set; }
        public Guid? ParameterID74 { get; set; }
        public Guid? ParameterID75 { get; set; }
        public Guid? ParameterID76 { get; set; }
        public Guid? ParameterID77 { get; set; }
        public Guid? ParameterID78 { get; set; }
        public Guid? ParameterID79 { get; set; }
        public Guid? ParameterID80 { get; set; }
        public Guid? ParameterID81 { get; set; }
        public Guid? ParameterID82 { get; set; }
        public Guid? ParameterID83 { get; set; }
        public Guid? ParameterID84 { get; set; }
        public Guid? ParameterID85 { get; set; }
        public Guid? ParameterID86 { get; set; }
        public Guid? ParameterID87 { get; set; }
        public Guid? ParameterID88 { get; set; }
        public Guid? ParameterID89 { get; set; }
        public Guid? ParameterID90 { get; set; }
        public Guid? ParameterID91 { get; set; }
        public Guid? ParameterID92 { get; set; }
        public Guid? ParameterID93 { get; set; }
        public Guid? ParameterID94 { get; set; }
        public Guid? ParameterID95 { get; set; }
        public Guid? ParameterID96 { get; set; }
        public Guid? ParameterID97 { get; set; }
        public Guid? ParameterID98 { get; set; }
        public Guid? ParameterID99 { get; set; }
        public Guid? ParameterID100 { get; set; }
        #endregion
        public string CriteriaName { get; set; } = null!;
    }
}